services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/nginx/nginx
    container_name: ${CONTAINER_NAME}
    image: vila/nginx

    ports:
      - ${PORT_WEB}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netmegacrossover2:
        ipv4_address: ${IP_WEB}
networks:
  netmegacrossover2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
