services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node/node
    container_name: ${CONTAINER_NAME}
    image: vila/node

    ports:
      - ${PORT_WEB}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netmegacrossover3:
        ipv4_address: ${IP_WEB}
networks:
  netmegacrossover3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
